management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus

  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

integration:
  keycloak.url: ${KEYCLOACK_URL:http://localhost:8080/out/keycloak}
  logic.url: ${LOGIC_URL:http://localhost:8080/out/logic}